import { ScaleRoom } from "./scale-room.js";
import { ScaleFileStore } from "./scale-file-store.js";

const MAX_FILE_BYTES = 10 * 1024 * 1024;
const ALLOWED_FILES = new Set(["application/pdf", "image/jpeg", "image/png", "image/webp"]);
function secure(response){if(response.status===101)return response;const h=new Headers(response.headers);h.set("x-content-type-options","nosniff");h.set("referrer-policy","no-referrer");h.set("strict-transport-security","max-age=31536000; includeSubDomains");h.set("x-frame-options","DENY");h.set("permissions-policy","camera=(), microphone=(), geolocation=()");h.set("content-security-policy","default-src 'self'; img-src 'self' data: blob:; script-src 'self'; style-src 'self'; connect-src 'self' ws: wss:; font-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'none'; object-src 'none'");return new Response(response.body,{status:response.status,statusText:response.statusText,headers:h});}
function json(data,status=200){return secure(new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}}));}
function room(env){return env.SCALE_ROOM.getByName("cs-coophavila-escala-principal");}
function files(env){return env.SCALE_FILES.getByName("cs-coophavila-escala-arquivos");}
function sameOrigin(request){const origin=request.headers.get("origin");return !origin||origin===new URL(request.url).origin;}
async function proxy(request,env){const u=new URL(request.url);const path=u.pathname.replace(/^\/api/,"")||"/";const target=new URL(path+u.search,"https://scale-room.internal");const init={method:request.method,headers:new Headers(request.headers)};if(!["GET","HEAD"].includes(request.method))init.body=request.body;return secure(await room(env).fetch(new Request(target,init)));}
async function access(request,env,id){const r=await room(env).fetch(new Request(`https://scale-room.internal/requests/${encodeURIComponent(id)}/attachment-access`,{headers:new Headers(request.headers)}));const d=await r.json().catch(()=>({}));if(!r.ok)throw Object.assign(new Error(d.error||"Acesso negado."),{status:r.status});return d;}
async function upload(request,env,id){try{await access(request,env,id);const len=Number(request.headers.get("content-length")||0);if(len>MAX_FILE_BYTES+1_000_000)return json({error:"Documento acima de 10 MB."},413);const form=await request.formData();const file=form.get("file");if(!file||typeof file.arrayBuffer!=="function")return json({error:"Selecione um PDF ou imagem."},400);if(!file.size||file.size>MAX_FILE_BYTES)return json({error:"Documento deve ter até 10 MB."},413);if(!ALLOWED_FILES.has(file.type))return json({error:"Formato permitido: PDF, JPG, PNG ou WEBP."},415);const store=await files(env).fetch(new Request(`https://scale-file.internal/file/${encodeURIComponent(id)}`,{method:"PUT",headers:{"content-type":file.type,"x-file-name":encodeURIComponent(String(file.name||"documento"))},body:await file.arrayBuffer()}));const sd=await store.json().catch(()=>({}));if(!store.ok)return json({error:sd.error||"Falha ao armazenar documento."},store.status);const h=new Headers(request.headers);h.set("content-type","application/json");const rec=await room(env).fetch(new Request(`https://scale-room.internal/requests/${encodeURIComponent(id)}/attachment-record`,{method:"POST",headers:h,body:JSON.stringify({key:id,name:String(file.name||"documento").slice(0,240),mime:file.type,size:file.size})}));const rd=await rec.json().catch(()=>({}));if(!rec.ok){await files(env).fetch(new Request(`https://scale-file.internal/file/${encodeURIComponent(id)}`,{method:"DELETE"})).catch(()=>{});return json({error:rd.error||"Falha ao vincular documento."},rec.status);}return json({ok:true,attachment:{name:file.name,mime:file.type,size:file.size}},201);}catch(e){return json({error:e.message||"Falha no envio do documento."},e.status||500);}}
async function download(request,env,id){try{const d=await access(request,env,id);if(!d.attachment?.key)return json({error:"Documento não encontrado."},404);const r=await files(env).fetch(new Request(`https://scale-file.internal/file/${encodeURIComponent(d.attachment.key)}`));if(!r.ok)return json({error:"Documento não encontrado."},r.status);const h=new Headers(r.headers);h.set("content-disposition",`inline; filename*=UTF-8''${encodeURIComponent(d.attachment.name||"documento")}`);h.set("cache-control","private, no-store");return secure(new Response(r.body,{status:200,headers:h}));}catch(e){return json({error:e.message||"Falha ao abrir documento."},e.status||500);}}
export {ScaleRoom,ScaleFileStore};
export default {async fetch(request,env){const u=new URL(request.url);if(!["GET","HEAD","OPTIONS"].includes(request.method)&&!sameOrigin(request))return json({error:"Origem da solicitação não permitida."},403);if(u.pathname==="/api/health"&&request.method==="GET")return json({ok:true,site:"escala-medica-cs-coophavila",storage:"durable-object-sqlite",realtime:"websocket"});const m=u.pathname.match(/^\/api\/requests\/([^/]+)\/attachment$/);if(m&&request.method==="POST")return upload(request,env,m[1]);if(m&&request.method==="GET")return download(request,env,m[1]);if(u.pathname.startsWith("/api/"))return proxy(request,env);return secure(await env.ASSETS.fetch(request));}};